spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 2715445931zyh
    url: jdbc:mysql://localhost:3306/openapi?serverTimezone=Asia/Shanghai
  # session 失效时间为 1天
  session:
    timeout: 86400
    store-type: redis       # 默认是 none，这里改成存到 redis 中
  redis:
    database: 0
    host: localhost
    port: 6379
  jackson:
    time-zone: GMT+8

server:
  port: 8080

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    auto-mapping-behavior: full

  global-config:
    db-config:
      logic-delete-field: isdelete
      logic-delete-value: 1
      logic-not-delete-value: 0

knife4j:
  enable: true
